# Generated by Django 3.0.5 on 2020-04-09 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regional_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zone_Number', models.IntegerField()),
                ('County', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Position',
            fields=[
                ('Position', models.CharField(choices=[('CEO', 'CEO'), ('Regional Manager', 'Regional Manager'), ('Deparment Manager', 'Department Manager'), ('NOC Technician', 'NOC Technician'), ('Customer Service Manager', 'Customer Service Manager'), ('Customer Service Technician', 'Customer Service Technician')], max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.Staff_Position')),
            ],
        ),
    ]
